services:
  #  Subir API
  #  spring-app:
  #    container_name: spring-app
  #    image: spring-app
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8080:8080"
  #    networks:
  #      - app_rede
  #    depends_on:
  #      - postgres

  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_DB: dog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

    volumes:
      - ./01-basedog.sql:/docker-entrypoint-initdb.d/01-basedog.sql
    ports:
      - "5432:5432"
    networks:
      - app_rede
    restart: unless-stopped
#    command: postgres -c listen_addresses='*'

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - app_rede
#    restart: unless-stopped
#    depends_on:
#      - postgres

networks:
  app_rede:
    driver: bridge

volumes:
  pgadmin:

